# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: ./gradlew assembleDebug
        
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: ./gradlew test
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        
#  androidTest:
#    name: Instrumented Tests
#    runs-on: macOS-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Run Instrumented Tests
#        uses: reactivecircus/android-emulator-runner@v1
#        with:
#          api-level: 29
#          arch: x86
#          disable-animations: true
#          script: ./gradlew connectedAndroidTest --stacktrace
